CREATE TABLE 'historial_d' (
  TICKER SYMBOL capacity 10000 CACHE,
  PER SYMBOL capacity 256 CACHE,
  DATE TIMESTAMP,
  OPEN DOUBLE,
  HIGH DOUBLE,
  LOW DOUBLE,
  CLOSE DOUBLE,
  VOL DOUBLE,
  OPENINT INT
);