INSERT INTO historial_d
SELECT TICKER, 
PER, 
to_timestamp(concat(DATE, ' ', TIME), 'yyyyMMdd HHmmss') AS DATE, 
OPEN, 
HIGH, 
LOW, 
CLOSE, 
VOL, 
OPENINT 
FROM historial_raw_d;

SELECT TICKER, PER, DATE, CLOSE, 
avg(close) OVER (PARTITION BY TICKER, PER ORDER BY DATE ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) 
AS MovingAvg_5Day 
FROM historial_d
