CREATE TABLE etf_info (
  ticker SYMBOL,
  name VARCHAR,
  aum DOUBLE,
  aum_currencey VARCHAR,
  asset_class VARCHAR,
  focus VARCHAR,
  brand VARCHAR,
  category VARCHAR,
  country_of_registration SYMBOL CAPACITY 300,
  niche VARCHAR,
  region VARCHAR,
  strategy VARCHAR,
  leverage VARCHAR,
  portfolio_transparency VARCHAR,
  selection_criteria VARCHAR,
  weighting_scheme VARCHAR,
  index_provider VARCHAR,
  currency_hedged VARCHAR,
  derivative_holding VARCHAR,
  tax_form VARCHAR,
  ucits_compliance VARCHAR,
  fund_flows_one_month DOUBLE,
  fund_flows_one_month_currency VARCHAR,
  net_assets_value DOUBLE,
  net_assets_value_currency VARCHAR
), INDEX (ticker CAPACITY 9000);