CREATE TABLE 'raw_stock_info' ( 
	ticker SYMBOL CAPACITY 4096 CACHE INDEX CAPACITY 16384,
	name VARCHAR,
	market_cap DOUBLE,
	market_cap_currencey VARCHAR,
	sector SYMBOL CAPACITY 32 CACHE,
	industry SYMBOL CAPACITY 256 CACHE,
	exchange SYMBOL CAPACITY 16 CACHE,
	country SYMBOL CAPACITY 512 CACHE,
	float_shares_outstanding DOUBLE,
	float_shares_percentage DOUBLE,
	shares_outstanding LONG,
	index VARCHAR,
	price_to_sales DOUBLE,
	price_to_earnings DOUBLE,
	price_to_book DOUBLE,
	average_volume_month DOUBLE,
	VWAP DOUBLE,
	VWMA_20 DOUBLE,
	CAPEX DOUBLE,
	CAPEX_currency VARCHAR,
	CAPEX_growth_annual DOUBLE,
	dividend_per_share DOUBLE,
	dividend_per_share_currency VARCHAR,
	dividend_yield DOUBLE,
	book_per_share DOUBLE,
	book_per_share_currency VARCHAR
)
WITH maxUncommittedRows=500000, o3MaxLag=600000000us