//@version=6
indicator("DeMark Sell", overlay=true)

// === Helper Functions ===
isSellSetup = close > close[4]

// Determine a bullish or bearish price flip
isBullishFlip = isSellSetup and close[1] < close[5]

// === Sell Setup ===
var int sellSetupCounter = 0
var bool isSellSetupActive= false

if isBullishFlip
    sellSetupCounter := 1
    isSellSetupActive:= true
else if isSellSetupActive and isSellSetup
    sellSetupCounter += 1
    isSellSetupActive:= sellSetupCounter <= 9
else if close <= close[4]
    sellSetupCounter := 0
    isSellSetupActive:= false

isSellSetupComplete = sellSetupCounter == 9

// === Sell Setup Perfection ===
isPerfectSellSetup = math.max(high, high[1]) >= math.max(high[2], high[3])

isSellCounterDown = high[2] < close

// === Sell Countdown ===
var int sellCountdownCounter= 0
var bool isSellCountdownActive = false
var bool isSellOnhold = false
var bool isSellDeferral = false

if isSellSetupComplete and not isSellCountdownActive
    if isSellCounterDown
        // Countdown qualifier: close must be > high[2]
        sellCountdownCounter:= 1
    else
        sellCountdownCounter:= 0
    isSellCountdownActive := true
    isSellOnhold := false
else if isSellCountdownActive
    if isSellCounterDown and sellCountdownCounter < 13 
        // Countdown qualifier: close must be > high[2]  
        sellCountdownCounter += 1
        isSellOnhold := false
    else if isSellCounterDown
        isSellOnhold := false
    else
        isSellOnhold := true

// This is used to determine the bar index of the 8th sell setup bar for potential countdown deferral
var float sellCountdown8Close = na
if sellCountdownCounter == 8
    sellCountdown8Close := close

if sellCountdownCounter == 13 and high > sellCountdown8Close
    // Check if the sell countdown deferral condition is met
    isSellDeferral := false
else
    isSellDeferral := true

// === Plot Sell Setup Count using plotshape() ===
plotshape(isSellSetupActive and sellSetupCounter == 1 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="1", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 2 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="2", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 3 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="3", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 4 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="4", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 5 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="5", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 6 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="6", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 7 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="7", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter == 8 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="8", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
//plotshape(isSellSetupActive and not isSellCountdownActive and sellSetupCounter==8 ? low : na, title="Buy Setup", location=location.abovebar, style=shape.labeldown, text="8", color=color.green, textcolor=color.white, size=size.tiny)
plotshape(isSellSetupActive and sellSetupCounter==9 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="9", color=color.green, textcolor=color.white, size=size.tiny)

// === Plot Sell Countdown using plotshape() ===
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 1 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="1", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 2 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="2", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 3 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="3", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 4 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="4", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 5 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="5", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 6 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="6", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 7 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="7", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 8 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="8", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 9 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="9", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 10 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="10", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 11 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="11", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellOnhold and sellCountdownCounter == 12 ? high * 0.99: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="12", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)

// === Sell Countdown 13 Deferral and Sell Countdown 13 Final using plotshape() ===
plotshape(isSellCountdownActive and isSellDeferral and sellCountdownCounter == 13 ? high : na, title="Sell Countdown Deferral", location=location.abovebar, style=shape.labeldown, text="+", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isSellCountdownActive and not isSellDeferral and sellCountdownCounter == 13 ? high : na, title="Sell Countdown Final", location=location.abovebar, style=shape.labeldown, text="13", color=color.red, textcolor=color.white, size=size.tiny)
// Reset countdown after 13
if sellCountdownCounter== 13 and not isSellDeferral
    // Reset sell countdown if it reaches 13 and is not deferred
    sellCountdownCounter:= 0
    isSellCountdownActive := false
    isSellDeferral := false
    sellCountdown8Close := na