//@version=6
indicator("DeMark Sequential", overlay=true)

// === Helper Functions ===
inBuySetup = close < close[4]
inSellSetup = close > close[4]

// Determine a bullish or bearish price flip
bearishFlip = inBuySetup and close[1] > close[5]
bullishFlip = inSellSetup and close[1] < close[5]

// === Buy Setup ===
var int buySetupCount = 0
var bool buySetupActive = false

if bearishFlip
    buySetupCount := 1
    buySetupActive := true
else if buySetupActive and inBuySetup
    buySetupCount += 1
    buySetupActive := buySetupCount <= 9
else if close >= close[4]
    buySetupCount := 0
    buySetupActive := false

isBuySetupComplete = buySetupCount == 9

// === Sell Setup ===
var int sellSetupCount = 0
var bool sellSetupActive = false

if bullishFlip
    sellSetupCount := 1
    sellSetupActive := true
else if sellSetupActive and inSellSetup
    sellSetupCount += 1
    sellSetupActive := sellSetupCount <= 9
else if close <= close[4]
    sellSetupCount := 0
    sellSetupActive := false

isSellSetupComplete = sellSetupCount == 9

// === Buy Setup Perfection ===
buySetupPerfect = math.min(low, low[1]) <= math.min(low[2], low[3])

// === Sell Setup Perfection ===
sellSetupPerfect = math.max(high, high[1]) >= math.max(high[2], high[3])

// === Buy Countdown ===
var int buyCountdown = 0
var bool inBuyCountdown = false
var bool buyOnhold = false

if isBuySetupComplete and not inBuyCountdown
    buyCountdown := 1
    inBuyCountdown := true
    buyOnhold := false
// Countdown qualifier: close must be < low[2]
else if inBuyCountdown
    if close < close[2]
        buyCountdown += 1
        buyOnhold := false
    else 
        buyOnhold := true


// === Sell Countdown ===
var int sellCountdown = 0
var bool inSellCountdown = false
var bool sellOnhold = false

if isSellSetupComplete and not inSellCountdown
    sellCountdown := 1
    inSellCountdown := true
    sellOnhold := false
// Countdown qualifier: close must be > high[2]
else if inSellCountdown
    if close > close[2]
        sellCountdown += 1
        sellOnhold := false
    else
        sellOnhold := true

// === Plot Setup Count using plotshape() ===
plotshape(buySetupActive and buySetupCount==1 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="1", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==2 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="2", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==3 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="3", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==4 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="4", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==5 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="5", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==6 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="6", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==7 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="7", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==8 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="8", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(buySetupActive and buySetupCount==9 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="9", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)


plotshape(sellSetupActive and sellSetupCount==1 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="1", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==2 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="2", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==3 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="3", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==4 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="4", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==5 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="5", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==6 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="6", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==7 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="7", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==8 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="8", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(sellSetupActive and sellSetupCount==9 ? high : na, title="Sell Setup", location=location.abovebar, style=shape.labeldown, text="9", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)


// === Plot Countdown using plotshape() ===

plotshape(inBuyCountdown and not buyOnhold and buyCountdown==1 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="1", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==2 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="2", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==3 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="3", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==4 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="4", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==5 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="5", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==6 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="6", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==7 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="7", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==8 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="8", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==9 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="9", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==10 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="10", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==11 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="11", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inBuyCountdown and not buyOnhold and buyCountdown==12 ? low - 1: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="12", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)


// === Plot Countdown using plotshape() ===
plotshape(inSellCountdown and not sellOnhold and sellCountdown==1 ? high + 1 : na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="1", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==2 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="2", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==3 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="3", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==4 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="4", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==5 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="5", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==6 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="6", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==7 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="7", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==8 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="8", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==9 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="9", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==10 ? high + 1 : na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="10", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==11 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="11", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(inSellCountdown and not sellOnhold and sellCountdown==12 ? high + 1: na, title="Sell Countdown", location=location.absolute, style=shape.labeldown, text="12", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)


// === Final Countdown 13 using plotshape() ===
plotshape(buyCountdown == 13 ? low : na, title="Buy Countdown 13", location=location.belowbar, style=shape.labelup, text="13", color=color.red, textcolor=color.white, size=size.normal)
plotshape(sellCountdown == 13 ? high : na, title="Sell Countdown 13", location=location.abovebar, style=shape.labeldown, text="13", color=color.red, textcolor=color.white, size=size.normal)

// Reset countdown after 13
if buyCountdown == 13
    buyCountdown := 0
    inBuyCountdown := false
if sellCountdown == 13
    sellCountdown := 0
    inSellCountdown := false
