//@version=6
indicator("DeMark Buy", overlay=true)

// === Helper Functions ===
isBuySetup = close < close[4]

// Determine a bullish or bearish price flip
isBearishFlip = isBuySetup and close[1] > close[5]

// === Buy Setup ===
var int buySetupCounter = 0
var bool isBuySetupActive = false

if isBearishFlip
    buySetupCounter := 1
    isBuySetupActive := true
else if isBuySetupActive and isBuySetup
    buySetupCounter += 1
    isBuySetupActive := buySetupCounter <= 9
else if close >= close[4]
    buySetupCounter := 0
    isBuySetupActive := false

isBuySetupComplete = buySetupCounter == 9

// === Buy Setup Perfection ===
isPerfectBuySetup = math.min(low, low[1]) <= math.min(low[2], low[3])

isBuyCounterDown = close < low[2]

// === Buy Countdown ===
var int buyCountdownCounter = 0
var bool isBuyCountdownActive = false
var bool isBuyOnhold = false
var bool isBuyDeferral = false

if isBuySetupComplete and not isBuyCountdownActive
    if isBuyCounterDown
        // Countdown qualifier: close must be < low[2]
        buyCountdownCounter := 1
    else
        buyCountdownCounter := 0
    isBuyCountdownActive := true
    isBuyOnhold := false
else if isBuyCountdownActive
    if isBuyCounterDown and buyCountdownCounter < 13
        // Countdown qualifier: close must be < low[2]
        buyCountdownCounter += 1
        isBuyOnhold := false
    else if isBuyCounterDown
        isBuyOnhold := false
    else 
        isBuyOnhold := true


// This is used to determine the bar index of the 8th buy countdown bar for potential countdown deferral
var float buyCounterdown8Close = na
if buyCountdownCounter == 8
    buyCounterdown8Close := close

if buyCountdownCounter == 13 and low <= buyCounterdown8Close
    // Check if the buy countdown deferral condition is met
    isBuyDeferral := true
else
    isBuyDeferral := false

// === Plot Buy Setup Count using plotshape() ===
plotshape(isBuySetupActive and buySetupCounter == 1 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="1", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 2 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="2", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 3 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="3", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 4 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="4", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 5 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="5", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 6 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="6", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 7 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="7", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 8 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="8", color=color.new(color.black, 100), textcolor=color.green, size=size.tiny)
//plotshape(isBuySetupActive and not isBuyCountdownActive and buySetupCounter==8 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="8", color=color.green, textcolor=color.white, size=size.tiny)
plotshape(isBuySetupActive and buySetupCounter == 9 ? low : na, title="Buy Setup", location=location.belowbar, style=shape.labelup, text="9", color=color.green, textcolor=color.white, size=size.tiny)

// === Plot Buy Countdown using plotshape() ===
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 1 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="1", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 2 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="2", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 3 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="3", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 4 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="4", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 5 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="5", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 6 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="6", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 7 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="7", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 8 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="8", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 9 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="9", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 10 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="10", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny) 
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 11 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="11", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyOnhold and buyCountdownCounter == 12 ? low * 1.01: na, title="Buy Countdown", location=location.absolute, style=shape.labelup, text="12", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)



// == Buy Countdown 13 Deferral and Buy Countdown 13 Final using plotshape() ===
plotshape(isBuyCountdownActive and isBuyDeferral and buyCountdownCounter == 13 ? low: na, title="Buy Countdown Deferral", location=location.belowbar, style=shape.labelup, text="+", color=color.new(color.black, 100), textcolor=color.red, size=size.tiny)
plotshape(isBuyCountdownActive and not isBuyDeferral and buyCountdownCounter == 13 ? low: na, title="Buy Countdown Final", location=location.belowbar, style=shape.labelup, text="13", color=color.red, textcolor=color.white, size=size.tiny)

// Reset countdown after 13
if buyCountdownCounter == 13 and not isBuyDeferral
    // Reset buy countdown if it reaches 13 and is not deferred
    buyCountdownCounter := 0
    isBuyCountdownActive := false
    isBuyDeferral := false
    buyCounterdown8Close := na