spring:
  application:
    name: m2-questdb

path:
  hostName: "192.168.51.168:9000"
  importHistoricalFile: "/Users/admin/historical_data"
  importHistoricalError: "/Users/admin/historical_error"
  importDailyFile: "/Users/admin/daily_data"
  importDailyError: "/Users/admin/daily_error"